### ISSUE TITLE
Can't paste into programs running with elevated priviliges.

### ISSUE THREAD

**Issue by MaverickMartyn** [CoreyHayward/PowerToys-Run-ClipboardManager#3]
Pasting to a program running as administrator doesn't work, even while running PowerToys as admin.
It can be easily reproduced using Notepad.

**Comment by CoreyHayward** [comment]
Thanks for reporting, I have been able to re-create this and will take a look when I get a chance

**Comment by CoreyHayward** [comment]
@MaverickMartyn Apologies for the delay in getting round to this. 
It looks as though the root cause of this issue is in how PowerToys Run dynamically loads in the plugins meaning as far as I can tell they don't run as administrator even when PowerToys itself has been configured to run as administrator. 

I have implemented a workaround for this so that you can properly paste into an administrative program using the context menu (CTRL+SHFT+ENTER) which hopefully will help you out until I can either look at the root issue in PowerToys Run or someone else does!
Unfortunately this workaround forces the UAC prompt each time its executed but I thought that it would be better than nothing!

**Comment by CoreyHayward** [comment]
Just for further reference, it looks like this is a feature of PowerToys and not a bug based on issues from the PowerToys Repo. PowerToys Run is always forced to run as a non-administrative level to prevent every single operation being executed as admin (see the 'fix' here https://github.com/microsoft/PowerToys/issues/3215) therefore the implemented solution is likely the only way this can be achieved.
